### ISSUE TITLE
How to sync definitions for role playing dimensions

### ISSUE THREAD

**Issue by snama2020** [BIDeveloperExtensions/bideveloperextensions#32] opened 2018-04-25 19:57 UTC
I am trying to sync definitions on a role playing dimension and I get an error when I do that. The main dimension from which the role playing dimension was created has the definitions synced using "Sync Definitions" and now I want to propagate the definitions to the role playing dimensions and that is when I get the error. I am not sure how I need to go about getting this done.

![image](https://user-images.githubusercontent.com/38735775/39269586-e652ce28-4898-11e8-87bd-37ca92f8a090.png)

**Comment by furmangg** [comment] 2018-04-25 20:10
Is it a legacy type data source that uses a plain SQL query? Or is it using the modern get data experience (Power Query)? What version of Visual Studio? What compatibility level on the model?

**Comment by snama2020** [comment] 2018-04-25 20:26
I honestly don't understand the first two questions but I will try to give some details about our environment. Please let me know if you need any further info.

SQL Server : 2016
Visual Studio version : VS Enterprise 2015 (Version - 14.0.25431.01 Update 3)
BI Developer Extensions : 2.1.1
Compatibility Level : 1200

**Comment by furmangg** [comment] 2019-05-02 03:15
I suspect this issue is related to the table using a Power Query source rather than a legacy source. I believe we've got a more helpful error message confirming this in the more recent Visual Studio 2017 and 2019 builds of BI Developer Extensions. But I'm going to leave this issue open as a feature request to support Power Query sources.

**Comment by furmangg** [comment] 2019-05-02 03:22
duplicate of #20

**Closed by furmangg** 2019-05-02 03:22 UTC
Labels: duplicate
