### ISSUE TITLE
Feature missing for "Create Fixed Width Columns" missing when right clicking connection manager

### ISSUE THREAD

**Issue by gturley8** [BIDeveloperExtensions/bideveloperextensions#58] opened 2019-04-06 01:54 UTC
There is no option for creating fixed width columns when right clicking connection manager in Visual Studio 2017.

**Comment by furmangg** [comment] 2019-04-11 02:59
Can you try the latest 2.3.0 release and let me know if that fixes it? My guess is that it will and I'll go ahead and close this issue. But let me know if it doesn't. If not, check the [documentation page](https://bideveloperextensions.github.io/features/CreateFixedWidthColumns/) about ensuring your connection manager is set to fixed width or ragged right.

To update to the latest release, in Visual Studio 2017 under the Tools... Extensions and Updates menu and the Update tab you should see v2.3.0 show up. It should auto-update or you can manually update it.

Ensure you have the latest version of [SSDT installed](https://docs.microsoft.com/en-us/sql/ssdt/download-sql-server-data-tools-ssdt?view=sql-server-2017) (version 15.9.0 or higher) for Visual Studio 2017. Then in Visual Studio 2017 go to Tools... Extensions and Updates... Updates tab... then ensure you install any updates to Microsoft Analysis Services Projects, Microsoft Reporting Services Projects, or Microsoft Integration Services Projects. This release is designed to work with version 2.8.11 SSAS extension or higher, version 2.5.6 SSRS extension or higher, and 2.1 SSIS extension or higher.

**Comment by tonyf132** [comment] 2019-04-15 14:09
Hi guys, I'm having this issue too. 

There's no option to Create Fixed Width file on the context menu

**Comment by gturley8** [comment] 2019-04-15 17:41
Hey furmangg, 

I verified I had the latest released, ensured my connection manager is set to ragged right, VS 2017 is up to date, SSDT is also up to date. I tried a clean uninstall/reinstall of all VS components, but the issue still remains. I'm using the 2.3.0 version of BI dev tools that you mentioned.

**Comment by furmangg** [comment] 2019-04-15 18:58
@tonyf132  and @gturley8 can you pass along the details about the SSIS extension version (and the SSAS and SSRS versions) you see in Help... About Microsoft Visual Studio? And can you go to Tools... Extensions and Updates and tell me what SSIS extension version number (and the SSAS and SSRS versions) you have installed?

Are you able to share the .dtsx package with me so I can see if I can repro this issue on my laptop?

**Comment by gturley8** [comment] 2019-04-15 19:06
![image](https://user-images.githubusercontent.com/49328992/56158262-98cc5200-5f8f-11e9-9c67-c0be565b22d6.png)
![image](https://user-images.githubusercontent.com/49328992/56158287-a386e700-5f8f-11e9-8941-ea908bb914d8.png)

I can create a test .dtsx with dummy data, what's the best way for me to get it to you?

**Comment by furmangg** [comment] 2019-04-15 23:03
@gturley8 thanks for the further info and help. Hopefully we can get to the bottom of this.

Based upon that Help dialog SSIS version 15.0.1100.123 I think that means your "Microsoft Integration Services Projects" extension is version 2.2 which is the version targeted with the BI Developer Extensions build. Can you click on "Microsoft Analysis Services Projects" and "Microsoft Reporting Services Projects" and confirm what versions you're running?

(If you don't have SSAS extension installed then try installing it and seeing if that fixes the problem. We don't have a very robust test matrix for not having all 3 SSDT extensions installed. So that could possibly be the root cause.)

Can you confirm you're not in "debug mode" (meaning you haven't been running the package recently without clicking the Stop button)?

Can you also try closing the SSIS package and reopening that SSIS package and then see if the connection manager has the "Create Fixed Width Columns" menu?

Can you go to Tools... Options... BIDS Helper... Version... if there are any error messages there, can you copy the errors and paste in this thread?

**Comment by gturley8** [comment] 2019-04-16 13:03
@furmangg, thanks for the troubleshooting suggestions.  Yes, my Integration Services Projects extension was version 2.2. I actually did not have SSAS installed, only SSRS and SSIS - but after I installed all three it still fails to show the menu. Confirmed I was not in debug mode. Also tried closing the SSIS package and re-opening with no success. 

I did see some errors, I'm getting this:

BIDS Helper encountered an error when Visual Studio started:
BIDS Helper encountered an error when Visual Studio started:
Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at BIDSHelper.BIDSHelperPackage.Initialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 126
Could not load file or assembly 'Microsoft.AnalysisServices, Version=15.15.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
Fusion Log:
WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].



Could not load file or assembly 'Microsoft.AnalysisServices, Version=15.15.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
Fusion Log:
WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].



Could not load file or assembly 'Microsoft.AnalysisServices, Version=15.15.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
Fusion Log:
WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].



Could not load file or assembly 'Microsoft.AnalysisServices, Version=15.15.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
Fusion Log:
WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].


BIDS Helper encountered an error when Visual Studio started:
BIDS Helper plugin constructor failed on AggregationManagerPlugin: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.Initialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 160

Inner exception:
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.Initialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 160
Inner exception:
Could not load file or assembly 'Microsoft.AnalysisServices, Version=15.15.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
   at BIDSHelper.AggregationManagerPlugin..ctor(BIDSHelperPackage package)BIDS Helper encountered an error when Visual Studio started:
BIDS Helper plugin constructor failed on DimensionHealthCheckPlugin: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.Initialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 160

Inner exception:
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.Initialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 160
Inner exception:
Could not load file or assembly 'Microsoft.AnalysisServices, Version=15.15.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
   at BIDSHelper.DimensionHealthCheckPlugin..ctor(BIDSHelperPackage package)BIDS Helper encountered an error when Visual Studio started:
BIDS Helper plugin constructor failed on SyncDescriptionsPlugin: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.Initialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 160

Inner exception:
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.Initialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 160
Inner exception:
Could not load file or assembly 'Microsoft.AnalysisServices, Version=15.15.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
   at BIDSHelper.SyncDescriptionsPlugin..ctor(BIDSHelperPackage package)BIDS Helper encountered an error when Visual Studio started:
BIDS Helper plugin constructor failed on TriStatePerspectivesPlugin: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.Initialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 160

Inner exception:
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.Initialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 160
Inner exception:
Could not load file or assembly 'Microsoft.AnalysisServices.Controls.AS, Version=15.1.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
   at BIDSHelper.TriStatePerspectivesPlugin..ctor(BIDSHelperPackage package)BIDS Helper encountered an error when Visual Studio started:
BIDS Helper plugin constructor failed on CalcHelpersPlugin: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.Initialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 160

Inner exception:
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.Initialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 160
Inner exception:
Could not load file or assembly 'Microsoft.AnalysisServices.Controls.AS, Version=15.1.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
   at BIDSHelper.SSAS.CalcHelpersPlugin..ctor(BIDSHelperPackage package)BIDS Helper encountered an error when Visual Studio started:
BIDS Helper plugin constructor failed on DeleteUnusedIndexesPlugin: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.Initialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 160

Inner exception:
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.Initialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 160
Inner exception:
Could not load file or assembly 'Microsoft.AnalysisServices, Version=15.15.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
   at BIDSHelper.SSAS.DeleteUnusedIndexesPlugin..ctor(BIDSHelperPackage package)BIDS Helper encountered an error when Visual Studio started:
BIDS Helper plugin constructor failed on DeployPerspectivesPlugin: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.Initialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 160

Inner exception:
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.Initialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 160
Inner exception:
Could not load file or assembly 'Microsoft.AnalysisServices.Controls.AS, Version=15.1.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
   at BIDSHelper.SSAS.DeployPerspectivesPlugin..ctor(BIDSHelperPackage package)BIDS Helper encountered an error when Visual Studio started:
BIDS Helper plugin constructor failed on DuplicateRole: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.Initialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 160

Inner exception:
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.Initialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 160
Inner exception:
Could not load file or assembly 'Microsoft.AnalysisServices, Version=15.15.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
   at BIDSHelper.SSAS.DuplicateRole..ctor(BIDSHelperPackage package)BIDS Helper encountered an error when Visual Studio started:
BIDS Helper plugin constructor failed on EstimatedCountsPlugin: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.Initialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 160

Inner exception:
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.Initialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 160
Inner exception:
Could not load file or assembly 'Microsoft.AnalysisServices.Controls.AS, Version=15.1.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
   at BIDSHelper.SSAS.EstimatedCountsPlugin..ctor(BIDSHelperPackage package)BIDS Helper encountered an error when Visual Studio started:
BIDS Helper plugin constructor failed on M2MMatrixCompressionPlugin: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.Initialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 160

Inner exception:
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.Initialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 160
Inner exception:
Could not load file or assembly 'Microsoft.AnalysisServices.Controls.AS, Version=15.1.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
   at BIDSHelper.SSAS.M2MMatrixCompressionPlugin..ctor(BIDSHelperPackage package)BIDS Helper encountered an error when Visual Studio started:
BIDS Helper plugin constructor failed on VisualizeAttributeLatticePlugin: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.Initialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 160

Inner exception:
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.Initialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 160
Inner exception:
Could not load file or assembly 'Microsoft.AnalysisServices, Version=15.15.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
   at BIDSHelper.SSAS.VisualizeAttributeLatticePlugin..ctor(BIDSHelperPackage package)

**Comment by furmangg** [comment] 2019-04-16 13:12
I assume those errors were from before you installed the SSAS extension? And what versions of the SSRS and SSAS Extensions are you running now?

I’m not spotting any obvious explanations. I may have to begin work on a debug build of BI Developer Extensions to help you troubleshoot.

**Comment by gturley8** [comment] 2019-04-16 13:15
SSRS and SSAS are both 2.0

**Comment by furmangg** [comment] 2019-04-16 13:24
Ah ha. That’s quite a bit behind. See the version numbers you are shooting for here:
https://bideveloperextensions.github.io/downloads/

In the “Ensure you...” paragraph you will see how you need to install the latest SSDT installer then run it then ipgrade individual extensions to get to those version numbers.

**Comment by furmangg** [comment] 2019-04-16 16:32
@gturley8 correction... you just need to update the SSAS and SSRS extensions from the Tools... Extensions and Updates menu... you already have the latest SSDT installer version I believe.

**Comment by furmangg** [comment] 2019-04-19 02:12
A couple of updates... 
1. Create Fixed Width Columns feature may not be showing up when the .dtsx package isn't selected in Solution Explorer. (For example, the project is selected rather than the .dtsx.) We've fixed this bug and it will be in the next release, but I wanted to let you know in case this unblocks you immediately.
2. We're making progress on improving how BI Developer Extensions handles having less all SSAS, SSIS and SSRS extensions installed. I'm hoping to have a beta build out soon for testing.

**Comment by gturley8** [comment] 2019-04-19 13:02
@furmangg 

Thanks so much! Ensuring that the .dtsx was selected in Solution Explorer solved my issue with "Create Fixed Width Columns" not displaying.

**Comment by furmangg** [comment] 2019-04-22 19:57
We have released a beta release which fixes the issues identified in this thread. The Create Fixed Width Columns menu should show up even if you don't have the .dtsx selected. And you shouldn't get ugly error messages in the Tools... Options... BIDS Helper... Version screen as long as you've got the latest SSDT installed and have updated any SSAS/SSIS/SSRS extensions individually. You don't have to have all 3 SSAS/SSIS/SSRS extensions installed for the expected BI Developer Extensions features to work as expected.

We plan to allow the week of 2019-04-22 for beta testing before releasing this to the public. Please download the release from here and please read the release notes there:
https://github.com/BIDeveloperExtensions/bideveloperextensions/releases/tag/v2.3.0_beta

I'm going to close this thread for now. Feel free to continue to comment on it or start a new thread if the feedback is on a different topic. We appreciate everyone's time in beta testing this release.

**Closed by furmangg** 2019-04-22 19:57 UTC

**Comment by furmangg** [comment] 2019-04-24 22:34
If anyone is beta testing, I uploaded a new beta release installer to the link mentioned above.
